# Generated by Django 3.0.2 on 2020-01-17 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.CharField(choices=[('DII', 'Departamenti i Inxhinierise Informatike'), ('DET', 'Departamenti i Inxhinierise Elektrionike dhe Telekomunikacionit'), ('DBI', 'Departamenti i Bazave te Informatikes')], max_length=3)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
